# Generated by Django 3.0.10 on 2020-10-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_working', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('In progress', 'In progress'), ('Finished', 'Finished')], max_length=50, null=True)),
                ('exercise', models.ManyToManyField(to='workouts.Exercise')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Member')),
            ],
        ),
    ]
